name: Taxesplugin
version: ${project.version}
main: com.dehys.taxesplugin.Plugin
api-version: 1.13
depend: [Vault]
authors: [nikoci, dehys]
description: A simple taxes plugin to keep economy balanced using Vault
website: https://github.com/nikoci/TaxesPlugin
